# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5cc292c1a6b49924586e1b6ec890272623bd83a3e21f361c2d829a174b69582f24ebee584d36d3f29315b10a6e6145e7cba727e7556022322e1070d45af1a82

test:
  secret_key_base: 0d2389d917cb8b95b53ced32c4e7d7a81a817c7583e461677efb4296b16eeda9bad134fff8868ed71dc2ae0a4ca168f055c9a333f688e8a8972840765e810b08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
